### ISSUE TITLE
Request and response node_id don't match.

### ISSUE THREAD

**Issue by lixiumei123** [neugates/neuron#306]
- System: Ubuntu Server 18.04
- Architecture: X86_64
- Lastest commit: 8ef22c88c54a0d76a08df9204bd4dd484cbf5095

![](https://user-images.githubusercontent.com/82565631/156521091-6cd66d77-5cb1-4bcd-bd09-09b6b30bece9.jpeg)

**Comment by fengzeroz** [comment]
When persisting data, the ID is not persisted, resulting in the ID changing after restarting neuron
