### ISSUE TITLE
Plugin persistence unsuccessful.

### ISSUE THREAD

**Issue by lixiumei123** [neugates/neuron#308]
- System: Ubuntu Server 18.04
- Architecture: X86_64
- Lastest commit: e67f1b300016d4f3b2592521905564bd1374c9b7
- Description: Adding a plugin is successfully written to the persistence file, but after restarting, the newly added plugin is not retrieved.

![](https://user-images.githubusercontent.com/82565631/156544456-26e22ff6-abf2-40de-bee8-16e039805083.jpeg)

Here's the log file:

[neuron.log](https://github.com/neugates/neuron/files/8176913/neuron.log)

Nodes:  You can watch from 16:50 onwards.

**Comment by fengzeroz** [comment]
When loading a persistent plugin fails, subsequent plugins fail to load
