### ISSUE TITLE
Crash when deleting node.

### ISSUE THREAD

**Issue by lixiumei123** [neugates/neuron#311]
- System: Ubuntu Server 18.04
- Architecture: X86_64
- Lastest commit: 884a36d5d25161ece7ef073f5169219d1a0dd2a7
- Description: Creating an adapter of type modbus-plus-tcp and deleting it without setting this adapter will cause the program to crash.

Here's the log:
![](https://user-images.githubusercontent.com/82565631/156709639-a1e64c32-b2d8-4648-bedb-b8cbe0192c0a.jpeg)

**Comment by fengzeroz** [comment]
fixed
